version: '3'
services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: share_energy_challenge
      MONGO_INITDB_ROOT_USERNAME: stanley
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
